trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: Check out repo

  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: Install Node

  - task: Npm@1
    inputs:
      command: ci
    displayName: Install dependencies

  - task: Npm@1
    inputs:
      command: custom
      customCommand: run build
    displayName: Build
